# Generated by Django 5.1.1 on 2024-09-12 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chai_variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ml', 'masala'), ('pl', 'plain'), ('el', 'elaichi'), ('gi', 'ginger'), ('ki', 'kiwi')], max_length=2)),
            ],
        ),
    ]
