# Generated by Django 5.1.1 on 2024-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai_variety',
            name='description',
            field=models.TextField(default='description not provided'),
        ),
    ]
